/*Utilizando o desenvolvimento da GUI com o NetBeans, use as
classes Relogio e Mostrador das aulas anteriores. Crie uma tela
que apresenta o mostrador do relógio (hora e minuto) em um
JLabel e que tenha três botões: TicTac, que aumenta um
minuto a cada clique; Hora, que acerta a hora (0 a 23); e
Minuto, que acerta o minuto (0 a 59). Use sempre o método
mostra() da classe Relogio para atualizar o mostrador da tela.
Consulte a documentação do Java para aumentar o tamanho e
a cor da fonte.*/

package exemplo_aula14;

public class Ex02 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ex02.class.getName());

    /**
     * Creates new form Ex02
     */
    public Ex02() {
        super("Exercicio 2");
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticTacButton = new javax.swing.JButton();
        hourButton = new javax.swing.JButton();
        minuteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ticTacButton.setText("TicTac");
        ticTacButton.addActionListener(this::ticTacButtonActionPerformed);

        hourButton.setText("Hora");
        hourButton.addActionListener(this::hourButtonActionPerformed);

        minuteButton.setText("Minuto");
        minuteButton.addActionListener(this::minuteButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ticTacButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hourButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minuteButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticTacButton)
                    .addComponent(hourButton)
                    .addComponent(minuteButton))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticTacButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticTacButtonActionPerformed
        
    }//GEN-LAST:event_ticTacButtonActionPerformed

    private void hourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourButtonActionPerformed
        
    }//GEN-LAST:event_hourButtonActionPerformed

    private void minuteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuteButtonActionPerformed
        
    }//GEN-LAST:event_minuteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ex02().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hourButton;
    private javax.swing.JButton minuteButton;
    private javax.swing.JButton ticTacButton;
    // End of variables declaration//GEN-END:variables
}
