/*Utilizando o desenvolvimento da GUI com o NetBeans, crie
uma tela para a hierarquia de classes PessoaFisica,
Desempregado, Empregado, Mensalista, Comissionado,
Horista e Tarefeiro.*/

package exemplo_aula14;

public class Ex05 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ex05.class.getName());

    /**
     * Creates new form Ex05
     */
    public Ex05() {
        super("Hierarquia de classes");
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        empregadoLabel = new javax.swing.JLabel();
        desempregadoLabel = new javax.swing.JLabel();
        mensalistaLabel = new javax.swing.JLabel();
        comissionadoLabel = new javax.swing.JLabel();
        horistaLabel = new javax.swing.JLabel();
        tarefeiroLabel = new javax.swing.JLabel();
        pessoaFisicaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitButton.setText("Sair");
        exitButton.addActionListener(this::exitButtonActionPerformed);

        empregadoLabel.setText("Empregado");

        desempregadoLabel.setText("Desempregado");

        mensalistaLabel.setText("Mensalista");

        comissionadoLabel.setText("Comissionado");

        horistaLabel.setText("Horista");

        tarefeiroLabel.setText("Tarefeiro");

        pessoaFisicaLabel.setText("Pessoa Fisica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(empregadoLabel)
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addGap(10, 10, 10)
                .addComponent(desempregadoLabel)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comissionadoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensalistaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(horistaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pessoaFisicaLabel)
                            .addComponent(tarefeiroLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pessoaFisicaLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empregadoLabel)
                    .addComponent(desempregadoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensalistaLabel)
                    .addComponent(horistaLabel)
                    .addComponent(tarefeiroLabel))
                .addGap(18, 18, 18)
                .addComponent(comissionadoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ex05().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comissionadoLabel;
    private javax.swing.JLabel desempregadoLabel;
    private javax.swing.JLabel empregadoLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel horistaLabel;
    private javax.swing.JLabel mensalistaLabel;
    private javax.swing.JLabel pessoaFisicaLabel;
    private javax.swing.JLabel tarefeiroLabel;
    // End of variables declaration//GEN-END:variables
}
